[package]
name = "rust-3xp1"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.31"
tracing-subscriber = "0.3.9"
clap = { version = "3.1.5", features = ["derive"] }